misc:
  n_grid: 200
  troubleshoot: True
  vihgp:
    iters: 800
    gamma: 0.4
seed: 12345
T: 25
B: 250
k: 10
n: 2
n_v: 2
noise_function_index: 3
test_function_index: 2
phi: 0.4
tau: 0.7
b0: 1
b1: 0.5
AF: "MUMBO"
