GP: vihgp
experiment_name: Pilot_02 VIHGP
misc:
  troubleshoot: True
  n_grid: 200
  vihgp:
    iters: 800
    n_u: 10
models:
  - IG
  - AEI
problem:
  b0: 1
  b1: 0.5
  k: 50
  n: 1
  n_v: 5
  n_max: 100
  n_min: 1
  noise_function_index: 0
  phi: 0.4
  seed: 12345
  tau: 0.7
  test_function_index: 1
  x_max: 1.0
  x_min: 0.0
study:
  M: 25
  T: 10
